name: Pipeline
description: Plantilla para despliegues de proyectos

inputs:
  GIT_TOKEN:
    required: true
    description: GIT_TOKEN

runs:
  using: "composite"
  steps:

    - name: Tagging
      shell: bash
      run: make gitflow_release