FROM alpine:3.20.2

RUN apk update && apk upgrade && apk add --no-cache curl=8.9.0-r0 && rm /var/cache/apk/*

RUN curl -s https://releases.hashicorp.com/terraform/1.9.4/terraform_1.9.4_linux_amd64.zip -o terraform_1.9.4_linux_amd64.zip && \
  unzip terraform_1.9.4_linux_amd64.zip && \
  mv terraform /usr/bin/terraform && \
  chmod +x /usr/bin/terraform

WORKDIR /app
ENTRYPOINT [ "/usr/bin/terraform" ]